# Generated by Django 4.1.1 on 2022-10-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='restaurant/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
