# Generated by Django 4.1.1 on 2022-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Без описания', verbose_name='Описание'),
        ),
    ]
