# Generated by Django 4.1.1 on 2022-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(default=[1], to='main.category', verbose_name='Категории'),
        ),
    ]
