# Generated by Django 4.1.1 on 2022-10-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legal_age',
            field=models.BooleanField(default=False, verbose_name='Можно'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_description',
            field=models.TextField(blank=True, default='Неизвестно', verbose_name='Sub.Описание'),
        ),
    ]
