# Generated by Django 4.1.1 on 2022-10-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_of_id_alter_product_legal_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
